[tasks.dev]
install_crate = "watchexec-cli"
command = "watchexec"
args = ["-w", "src", "-r", "cargo", "run"]

[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]
